name: shellgpt release

on:
  workflow_dispatch:
  push:
    tags:
      - 'shellgpt-v*'

defaults:
  run:
    working-directory: shellgpt

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: build
        run: |
          uv build
      - name: Pulish
        run: |
          uv publish -t '${{ secrets.HATCH_INDEX_AUTH }}'
