name: Zig OS ci

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'zigos/**'
      - '.github/workflows/zigos-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'zigos/**'
      - '.github/workflows/zigos-ci.yml'

defaults:
  run:
    working-directory: zigos

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: mlugg/setup-zig@v2
      - name: fmt
        run: |
          zig fmt --check .
          zig build
